version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: newsnest_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_BASE_URL: http://127.0.0.1:8000
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "start"]
